config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import (
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageDeleteView,
    MessageUpdateView,
    MailingRecipientListView,
    MailingRecipientCreateView,
    MailingRecipientDetailView,
    MailingRecipientUpdateView,
    MailingRecipientDeleteView,
    NewsletterListView,
    NewsletterCreateView,
    NewsletterDetailView,
    NewsletterUpdateView,
    NewsletterDeleteView,
    HomePageListView,
    AttemptToSendListView,
    NewsletterIsDisabledView,
)

app_name = "mailings"

urlpatterns = [
    path(
        "mailing_recipient_list/",
        MailingRecipientListView.as_view(),
        name="mailing_recipient_list",
    ),
    path(
        "mailing_recipient_create/",
        MailingRecipientCreateView.as_view(),
        name="mailing_recipient_create",
    ),
    path(
        "mailing_recipient_detail/<int:pk>/",
        MailingRecipientDetailView.as_view(),
        name="mailing_recipient_detail",
    ),
    path(
        "mailing_recipient_update/<int:pk>/",
        MailingRecipientUpdateView.as_view(),
        name="mailing_recipient_update",
    ),
    path(
        "mailing_recipient_delete/<int:pk>/",
        MailingRecipientDeleteView.as_view(),
        name="mailing_recipient_delete",
    ),
    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message_detail/<int:pk>/", MessageDetailView.as_view(), name="message_detail"
    ),
    path(
        "message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("newsletter_list/", NewsletterListView.as_view(), name="newsletter_list"),
    path(
        "newsletter_create/", NewsletterCreateView.as_view(), name="newsletter_create"
    ),
    path(
        "newsletter_detail/<int:pk>/",
        NewsletterDetailView.as_view(),
        name="newsletter_detail",
    ),
    path(
        "newsletter_update/<int:pk>/",
        NewsletterUpdateView.as_view(),
        name="newsletter_update",
    ),
    path(
        "newsletter_delete/<int:pk>/",
        NewsletterDeleteView.as_view(),
        name="newsletter_delete",
    ),
    path(
        "newsletter_is_disabled/<int:pk>/",
        NewsletterIsDisabledView.as_view(),
        name="newsletter_is_disabled",
    ),
    path("", HomePageListView.as_view(), name="home_page"),
    path("attempt_to_send/", AttemptToSendListView.as_view(), name="attempt_to_send"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import (
    UserCreateView,
    UserUpdateView,
    UserDetailView,
    UsersListView,
    UsersBlockedView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("profile_detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("profile_update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("users_list/", UsersListView.as_view(), name="users_list"),
    path("user_blocked/<int:pk>/", UsersBlockedView.as_view(), name="user_blocked"),
]

mailings/models.py
from django.db import models

from users.models import User


class MailingRecipient(models.Model):

    email = models.CharField(
        unique=True, max_length=150, verbose_name="Email", help_text="Введите email"
    )
    full_name = models.CharField(
        max_length=150, verbose_name="Ф.И.О", help_text="Введите Ф.И.О"
    )
    comment = models.TextField(
        verbose_name="Комментарий", help_text="Напишите комментарий"
    )
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.full_name}, {self.email}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["email", "full_name"]
        permissions = [
            ("can_view_mailing_recipient", "Can view mailing recipient"),
        ]


class Message(models.Model):

    topic = models.CharField(
        max_length=150, verbose_name="Тема письма", help_text="Введите тему письма"
    )
    content = models.TextField(
        verbose_name="Текст письма", help_text="Введите текст письма"
    )
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.topic}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["topic"]
        permissions = [
            ("can_view_message", "Can view message"),
        ]


class Newsletter(models.Model):

    sending_date = models.DateTimeField(
        verbose_name="Дата и время первой отправки",
        help_text="Впишите дату и время первой отправки",
    )
    end_date_of_send = models.DateTimeField(
        verbose_name="Дата и время окончания отправки",
        help_text="Впишите дату и время окончания отправки",
    )
    status = models.CharField(max_length=9, verbose_name="Статус")
    message = models.ForeignKey(
        Message,
        verbose_name="Сообщение",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    recipients = models.ManyToManyField(MailingRecipient, verbose_name="Получатели")
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.CASCADE
    )
    newsletter_is_disabled = models.BooleanField(
        default=False, verbose_name="Рассылка отключена"
    )

    def __str__(self):
        return f"{self.status}, {self.message}, {self.recipients}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["sending_date", "end_date_of_send", "status"]
        permissions = [
            ("can_view_newsletter", "Can view newsletter"),
            ("can_newsletter_is_disabled", "Can newsletter is disabled"),
        ]


class AttemptToSend(models.Model):

    date_of_attempt = models.DateTimeField(
        verbose_name="Дата и время попытки", auto_now=True
    )
    status = models.CharField(max_length=10, verbose_name="Статус")
    mail_server_response = models.TextField(verbose_name="Ответ почтового сервера")
    newsletter = models.ForeignKey(
        Newsletter,
        verbose_name="Рассылка",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.status}, {self.date_of_attempt}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"
        ordering = ["date_of_attempt", "status"]

mailings/forms.py
from django import forms

from .models import Message, MailingRecipient, Newsletter


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = [
            "topic",
            "content",
        ]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields["topic"].widget.attrs.update({"class": "form-control"})
        self.fields["content"].widget.attrs.update({"class": "form-control"})


class MailingRecipientForm(forms.ModelForm):

    class Meta:
        model = MailingRecipient
        fields = ["email", "full_name", "comment"]

    def __init__(self, *args, **kwargs):
        super(MailingRecipientForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({"class": "form-control"})
        self.fields["full_name"].widget.attrs.update({"class": "form-control"})
        self.fields["comment"].widget.attrs.update({"class": "form-control"})


class NewsletterForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = [
            "sending_date",
            "end_date_of_send",
            "message",
            "recipients",
        ]

    def __init__(self, *args, **kwargs):
        super(NewsletterForm, self).__init__(*args, **kwargs)
        self.fields["sending_date"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Год-месяц-День часы:минуты:секунды",
            }
        )
        self.fields["end_date_of_send"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Год-месяц-День часы:минуты:секунды",
            }
        )
        self.fields["message"].widget.attrs.update({"class": "form-control"})
        self.fields["recipients"].widget.attrs.update({"class": "form-control"})


class NewsletterIsDisabledForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = [
            "newsletter_is_disabled",
        ]

    def __init__(self, *args, **kwargs):
        super(NewsletterIsDisabledForm, self).__init__(*args, **kwargs)
        self.fields["newsletter_is_disabled"].widget.attrs.update(
            {"class": "form-check"}
        )

mailings/views.py
from django.core import cache
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)

from mailings.forms import (
    MessageForm,
    MailingRecipientForm,
    NewsletterForm,
    NewsletterIsDisabledForm,
)
from mailings.models import Message, MailingRecipient, Newsletter, AttemptToSend
from mailings.services import NewsletterService


class MessageListView(ListView):
    model = Message
    context_object_name = "messages"
    template_name = "mailings_message/message_list.html"

    def get_queryset(self):
        queryset = cache.get("message_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("message_list_view", queryset, 60 * 15)


@method_decorator(cache_page(60 * 15), name="dispatch")
class MessageDetailView(DetailView):
    model = Message
    context_object_name = "message"
    template_name = "mailings_message/message_detail.html"


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailings:message_list")
    template_name = "mailings_message/message_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailings:message_list")
    template_name = "mailings_message/message_update.html"


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy("mailings:message_list")
    template_name = "mailings_message/message_delete.html"


class MailingRecipientListView(ListView):
    model = MailingRecipient
    context_object_name = "mailing_recipients"
    template_name = "mailings_mailing_recipient/mailing_recipient_list.html"

    def get_queryset(self):
        queryset = cache.get("mailing_recipient_list")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("mailing_recipient_list", queryset, 60 * 15)


@method_decorator(cache_page(60 * 15), name="dispatch")
class MailingRecipientDetailView(DetailView):
    model = MailingRecipient
    context_object_name = "mailing_recipient"
    template_name = "mailings_mailing_recipient/mailing_recipient_detail.html"


class MailingRecipientCreateView(CreateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailings:mailing_recipient_list")
    template_name = "mailings_mailing_recipient/mailing_recipient_create.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingRecipientUpdateView(UpdateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailings:mailing_recipient_list")
    template_name = "mailings_mailing_recipient/mailing_recipient_update.html"


class MailingRecipientDeleteView(DeleteView):
    model = MailingRecipient
    success_url = reverse_lazy("mailings:mailing_recipient_list")
    template_name = "mailings_mailing_recipient/mailing_recipient_delete.html"


class NewsletterListView(ListView):
    model = Newsletter
    context_object_name = "newsletters"
    template_name = "mailings_newsletter/newsletter_list.html"

    def get_queryset(self):

        queryset = cache.get("newsletter_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("newsletter_list_view", queryset, 60 * 15)

        newsletters = super().get_queryset()
        for newsletter in newsletters:
            NewsletterService.send_newsletter_emails(newsletter_id=newsletter.id)
        return newsletters and Newsletter.objects.filter(newsletter_is_disabled=False)


@method_decorator(cache_page(60 * 15), name="dispatch")
class NewsletterDetailView(DetailView):
    model = Newsletter
    context_object_name = "newsletter"
    template_name = "mailings_newsletter/newsletter_detail.html"


class NewsletterCreateView(CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy("mailings:newsletter_list")
    template_name = "mailings_newsletter/newsletter_create.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.status = "Создана"
        return super().form_valid(form)


class NewsletterUpdateView(UpdateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy("mailings:newsletter_list")
    template_name = "mailings_newsletter/newsletter_update.html"


class NewsletterDeleteView(DeleteView):
    model = Newsletter
    success_url = reverse_lazy("mailings:newsletter_list")
    template_name = "mailings_newsletter/newsletter_delete.html"


class HomePageListView(ListView):
    model = Newsletter
    template_name = "mailings_message/home_page.html"

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        context["number_of_mailings"] = len(Newsletter.objects.all())
        context["number_of_active_mailings"] = len(
            [
                newsletter
                for newsletter in Newsletter.objects.all()
                if newsletter.status == "Запущена"
            ]
        )
        context["number_of_recipients"] = len(MailingRecipient.objects.all())

        return context

    def get_queryset(self):
        queryset = cache.get("home_page_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("home_page_list_view", queryset, 60 * 15)


class AttemptToSendListView(ListView):
    model = AttemptToSend
    template_name = "mailings_message/attempt_to_send.html"
    context_object_name = "information"

    def get_queryset(self):
        queryset = cache.get("attempt_to_send_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("attempt_to_send_list_view", queryset, 60 * 15)


class NewsletterIsDisabledView(UpdateView):
    model = Newsletter
    form_class = NewsletterIsDisabledForm
    template_name = "mailings_newsletter/newsletter_is_disabled.html"
    success_url = reverse_lazy("mailings:newsletter_list")

    def form_valid(self, form):
        form.instance.status = "Завершена"
        return super().form_valid(form)

mailings/templates/mailings_mailing_recipient/mailing_recipient_create.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Создание получателя рассылки</h1></div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'mailings:mailing_recipient_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

mailings/templates/mailings_mailing_recipient/mailing_recipient_delete.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Вы точно хотите удалить этого получателя рассылок?</h1></div>
{% endblock %}

{% block content %}
<div class="container mt-5" style="text-align: center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailings:mailing_recipient_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

mailings/templates/mailings_mailing_recipient/mailing_recipient_detail.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Подробная информация о получателе рассылок</h1></div>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <p class="card-text h5" style="text-align: center">{{ mailing_recipient.full_name }}</p>
                    <p class="card-text">Email: {{ mailing_recipient.email }}</p>
                    <p class="card-text">Комментарий: {{ mailing_recipient.comment }}</p>
                    </div>
                </div>
        </div>
    </div>
</div>  {% endblock %}

mailings/templates/mailings_mailing_recipient/mailing_recipient_list.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Страница получателей рассылок</h1>
    <p class="lead text-body-secondary">Здесь располагаются получателе рассылок</p>
    <p><a href="{% url 'mailings:mailing_recipient_create' %}" class="btn btn-primary my-2">Добавить нового получателя рассылок</a></p>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"> {% for mailing_recipient in mailing_recipients %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body"><p class="card-text h5" style="text-align: center">{{ mailing_recipient.full_name }}</p>
                        <p class="card-text">Email: {{ mailing_recipient.email }}</p>
                        <p class="card-text">Комментарий: {{ mailing_recipient.comment|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            {% if user == mailing_recipient.owner or perms.mailings.can_view_mailing_recipient %}
                            <div class="btn-group"><a class="btn btn-primary"
                                                      href="{% url 'mailings:mailing_recipient_detail' mailing_recipient.pk %}"
                                                      role="button">Посмотреть</a>
                            {% endif %}
                            {% if user == mailing_recipient.owner %}
                            <a class="btn btn-primary"
                                                      href="{% url 'mailings:mailing_recipient_update' mailing_recipient.pk %}"
                                                      role="button">Редактировать</a>
                            <div class="btn-group"><a class="btn btn-primary"
                                                      href="{% url 'mailings:mailing_recipient_delete' mailing_recipient.pk %}"
                                                      role="button">Удалить</a></div>
                            {% endif %}
                            </div>
                            </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    </div>
{% endblock %}

mailings/templates/mailings_mailing_recipient/mailing_recipient_update.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Редактирование получателя рассылки</h1></div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'mailings:mailing_recipient_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}