config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import (
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageDeleteView,
    MessageUpdateView,
    MailingRecipientListView,
    MailingRecipientCreateView,
    MailingRecipientDetailView,
    MailingRecipientUpdateView,
    MailingRecipientDeleteView,
    NewsletterListView,
    NewsletterCreateView,
    NewsletterDetailView,
    NewsletterUpdateView,
    NewsletterDeleteView,
    HomePageListView,
    AttemptToSendListView,
    NewsletterIsDisabledView,
)

app_name = "mailings"

urlpatterns = [
    path(
        "mailing_recipient_list/",
        MailingRecipientListView.as_view(),
        name="mailing_recipient_list",
    ),
    path(
        "mailing_recipient_create/",
        MailingRecipientCreateView.as_view(),
        name="mailing_recipient_create",
    ),
    path(
        "mailing_recipient_detail/<int:pk>/",
        MailingRecipientDetailView.as_view(),
        name="mailing_recipient_detail",
    ),
    path(
        "mailing_recipient_update/<int:pk>/",
        MailingRecipientUpdateView.as_view(),
        name="mailing_recipient_update",
    ),
    path(
        "mailing_recipient_delete/<int:pk>/",
        MailingRecipientDeleteView.as_view(),
        name="mailing_recipient_delete",
    ),
    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message_detail/<int:pk>/", MessageDetailView.as_view(), name="message_detail"
    ),
    path(
        "message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("newsletter_list/", NewsletterListView.as_view(), name="newsletter_list"),
    path(
        "newsletter_create/", NewsletterCreateView.as_view(), name="newsletter_create"
    ),
    path(
        "newsletter_detail/<int:pk>/",
        NewsletterDetailView.as_view(),
        name="newsletter_detail",
    ),
    path(
        "newsletter_update/<int:pk>/",
        NewsletterUpdateView.as_view(),
        name="newsletter_update",
    ),
    path(
        "newsletter_delete/<int:pk>/",
        NewsletterDeleteView.as_view(),
        name="newsletter_delete",
    ),
    path(
        "newsletter_is_disabled/<int:pk>/",
        NewsletterIsDisabledView.as_view(),
        name="newsletter_is_disabled",
    ),
    path("", HomePageListView.as_view(), name="home_page"),
    path("attempt_to_send/", AttemptToSendListView.as_view(), name="attempt_to_send"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import (
    UserCreateView,
    UserUpdateView,
    UserDetailView,
    UsersListView,
    UsersBlockedView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("profile_detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("profile_update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("users_list/", UsersListView.as_view(), name="users_list"),
    path("user_blocked/<int:pk>/", UsersBlockedView.as_view(), name="user_blocked"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    username = models.CharField(
        max_length=100,
        verbose_name="Имя",
        blank=True,
        unique=False,
        default="not_username",
    )
    email = models.EmailField(unique=True, verbose_name="Email")
    avatar = models.ImageField(
        upload_to="users/",
        verbose_name="Аватар",
        blank=True,
        null=True,
        help_text="Загрузите свой аватар",
    )
    phone = models.CharField(
        max_length=35,
        verbose_name="Номер телефона",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    country = models.CharField(
        max_length=50,
        verbose_name="Страна",
        blank=True,
        null=True,
        help_text="Введите страну проживания",
    )

    is_active = models.BooleanField(
        verbose_name="Аккаунт пользователя активен",
        help_text="Если хотите заблокировать его то уберить галочку",
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_deactivation_user", "Can deactivation user"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите Email"}
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите пароль"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Повторите введенный пароль"}
        )


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["email", "avatar", "phone", "country"]

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({"class": "form-control"})
        self.fields["avatar"].widget.attrs.update({"class": "form-control"})
        self.fields["phone"].widget.attrs.update({"class": "form-control"})
        self.fields["country"].widget.attrs.update({"class": "form-control"})


class UserBlockedForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            "is_active",
        ]

    def __init__(self, *args, **kwargs):
        super(UserBlockedForm, self).__init__(*args, **kwargs)
        self.fields["is_active"].widget.attrs.update({"class": "form-check"})

users/views.py
from django.contrib.auth import login
from django.core import cache
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    ListView,
)

from users.forms import UserRegisterForm, UserUpdateForm, UserBlockedForm
from users.models import User


class UserCreateView(CreateView):
    template_name = "users/register.html"
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.send_welcome_email(user.email)
        return super().form_valid(form)

    def send_welcome_email(self, user_email):
        subject = "Добро пожаловать в наш сервис"
        message = "Спасибо, что зарегистрировались в нашем сервисе!"
        from_email = "Sasha.kel-1@yandex.ru"
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)


@method_decorator(cache_page(60 * 15), name="dispatch")
class UserDetailView(DetailView):
    template_name = "users/user_detail.html"
    model = User
    context_object_name = "user"


class UserUpdateView(UpdateView):
    template_name = "users/user_update.html"
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy("mailings:home_page")


class UsersListView(ListView):
    model = User
    template_name = "users/users_list.html"
    context_object_name = "users"

    def get_queryset(self):
        queryset = cache.get("users_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("users_list_view", queryset, 60 * 15)


class UsersBlockedView(UpdateView):
    model = User
    template_name = "users/user_blocked.html"
    form_class = UserBlockedForm
    success_url = reverse_lazy("users:users_list")

users/templates/users/login.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Вход в учетную запись</h1></div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'mailings:home_page' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Регистрация</h1></div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Зарегестрироваться</button>
            <a href="{% url 'mailings:home_page' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

users/templates/users/user_blocked.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Редактирование профиля пользователя {{ user.username }}</h1></div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'users:users_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Подробная информация о пользователе</h1></div>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <p class="card-text">Email: {{ user.email }}</p>
                    <p class="card-text">Аватар: {{ user.avatar }}</p>
                    <p class="card-text">Номер телефона: {{ user.phone }}</p>
                    <p class="card-text">Страна: {{ user.country }}</p>
                    </div>
                {% if not perms.users.can_deactivation_user %}
                <a class="btn btn-primary"
                   href="{% url 'users:user_update' user.pk %}" role="button">Редактировать</a>
                {% endif %}
                </div>
        </div>
    </div>
</div>  {% endblock %}

users/templates/users/user_update.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Редактирование профиля пользователя {{ user.username }}</h1></div>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'users:user_detail' user.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Список пользователей</h1>
    <p class="lead text-body-secondary">Здесь располагаются все пользователи</p>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"> {% for user in users %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body"><p class="card-text h5" style="text-align: center">{{ user.email }}</p>
                        <p class="card-text">Номер телефона: {{ user.phone }}</p>
                        <p class="card-text">Страна проживания: {{ user.country }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group"><a class="btn btn-primary"
                                                      href="{% url 'users:user_detail' user.pk %}"
                                                      role="button">Посмотреть</a>
                            <a class="btn btn-primary"
                                                      href="{% url 'users:user_blocked' user.pk %}"
                                                      role="button">Редактировать</a>
                            </div>
                            </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    </div>
{% endblock %}