config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailings.urls", namespace="mailings")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import (
    MessageListView,
    MessageDetailView,
    MessageCreateView,
    MessageDeleteView,
    MessageUpdateView,
    MailingRecipientListView,
    MailingRecipientCreateView,
    MailingRecipientDetailView,
    MailingRecipientUpdateView,
    MailingRecipientDeleteView,
    NewsletterListView,
    NewsletterCreateView,
    NewsletterDetailView,
    NewsletterUpdateView,
    NewsletterDeleteView,
    HomePageListView,
    AttemptToSendListView,
    NewsletterIsDisabledView,
)

app_name = "mailings"

urlpatterns = [
    path(
        "mailing_recipient_list/",
        MailingRecipientListView.as_view(),
        name="mailing_recipient_list",
    ),
    path(
        "mailing_recipient_create/",
        MailingRecipientCreateView.as_view(),
        name="mailing_recipient_create",
    ),
    path(
        "mailing_recipient_detail/<int:pk>/",
        MailingRecipientDetailView.as_view(),
        name="mailing_recipient_detail",
    ),
    path(
        "mailing_recipient_update/<int:pk>/",
        MailingRecipientUpdateView.as_view(),
        name="mailing_recipient_update",
    ),
    path(
        "mailing_recipient_delete/<int:pk>/",
        MailingRecipientDeleteView.as_view(),
        name="mailing_recipient_delete",
    ),
    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path(
        "message_detail/<int:pk>/", MessageDetailView.as_view(), name="message_detail"
    ),
    path(
        "message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("newsletter_list/", NewsletterListView.as_view(), name="newsletter_list"),
    path(
        "newsletter_create/", NewsletterCreateView.as_view(), name="newsletter_create"
    ),
    path(
        "newsletter_detail/<int:pk>/",
        NewsletterDetailView.as_view(),
        name="newsletter_detail",
    ),
    path(
        "newsletter_update/<int:pk>/",
        NewsletterUpdateView.as_view(),
        name="newsletter_update",
    ),
    path(
        "newsletter_delete/<int:pk>/",
        NewsletterDeleteView.as_view(),
        name="newsletter_delete",
    ),
    path(
        "newsletter_is_disabled/<int:pk>/",
        NewsletterIsDisabledView.as_view(),
        name="newsletter_is_disabled",
    ),
    path("", HomePageListView.as_view(), name="home_page"),
    path("attempt_to_send/", AttemptToSendListView.as_view(), name="attempt_to_send"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import (
    UserCreateView,
    UserUpdateView,
    UserDetailView,
    UsersListView,
    UsersBlockedView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("profile_detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("profile_update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("users_list/", UsersListView.as_view(), name="users_list"),
    path("user_blocked/<int:pk>/", UsersBlockedView.as_view(), name="user_blocked"),
]

mailings/models.py
from django.db import models

from users.models import User


class MailingRecipient(models.Model):

    email = models.CharField(
        unique=True, max_length=150, verbose_name="Email", help_text="Введите email"
    )
    full_name = models.CharField(
        max_length=150, verbose_name="Ф.И.О", help_text="Введите Ф.И.О"
    )
    comment = models.TextField(
        verbose_name="Комментарий", help_text="Напишите комментарий"
    )
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.full_name}, {self.email}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["email", "full_name"]
        permissions = [
            ("can_view_mailing_recipient", "Can view mailing recipient"),
        ]


class Message(models.Model):

    topic = models.CharField(
        max_length=150, verbose_name="Тема письма", help_text="Введите тему письма"
    )
    content = models.TextField(
        verbose_name="Текст письма", help_text="Введите текст письма"
    )
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.topic}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["topic"]
        permissions = [
            ("can_view_message", "Can view message"),
        ]


class Newsletter(models.Model):

    sending_date = models.DateTimeField(
        verbose_name="Дата и время первой отправки",
        help_text="Впишите дату и время первой отправки",
    )
    end_date_of_send = models.DateTimeField(
        verbose_name="Дата и время окончания отправки",
        help_text="Впишите дату и время окончания отправки",
    )
    status = models.CharField(max_length=9, verbose_name="Статус")
    message = models.ForeignKey(
        Message,
        verbose_name="Сообщение",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    recipients = models.ManyToManyField(MailingRecipient, verbose_name="Получатели")
    owner = models.ForeignKey(
        User, verbose_name="Владелец", blank=True, null=True, on_delete=models.CASCADE
    )
    newsletter_is_disabled = models.BooleanField(
        default=False, verbose_name="Рассылка отключена"
    )

    def __str__(self):
        return f"{self.status}, {self.message}, {self.recipients}"

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["sending_date", "end_date_of_send", "status"]
        permissions = [
            ("can_view_newsletter", "Can view newsletter"),
            ("can_newsletter_is_disabled", "Can newsletter is disabled"),
        ]


class AttemptToSend(models.Model):

    date_of_attempt = models.DateTimeField(
        verbose_name="Дата и время попытки", auto_now=True
    )
    status = models.CharField(max_length=10, verbose_name="Статус")
    mail_server_response = models.TextField(verbose_name="Ответ почтового сервера")
    newsletter = models.ForeignKey(
        Newsletter,
        verbose_name="Рассылка",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.status}, {self.date_of_attempt}"

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"
        ordering = ["date_of_attempt", "status"]

mailings/forms.py
from django import forms

from .models import Message, MailingRecipient, Newsletter


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = [
            "topic",
            "content",
        ]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields["topic"].widget.attrs.update({"class": "form-control"})
        self.fields["content"].widget.attrs.update({"class": "form-control"})


class MailingRecipientForm(forms.ModelForm):

    class Meta:
        model = MailingRecipient
        fields = ["email", "full_name", "comment"]

    def __init__(self, *args, **kwargs):
        super(MailingRecipientForm, self).__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({"class": "form-control"})
        self.fields["full_name"].widget.attrs.update({"class": "form-control"})
        self.fields["comment"].widget.attrs.update({"class": "form-control"})


class NewsletterForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = [
            "sending_date",
            "end_date_of_send",
            "message",
            "recipients",
        ]

    def __init__(self, *args, **kwargs):
        super(NewsletterForm, self).__init__(*args, **kwargs)
        self.fields["sending_date"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Год-месяц-День часы:минуты:секунды",
            }
        )
        self.fields["end_date_of_send"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Год-месяц-День часы:минуты:секунды",
            }
        )
        self.fields["message"].widget.attrs.update({"class": "form-control"})
        self.fields["recipients"].widget.attrs.update({"class": "form-control"})


class NewsletterIsDisabledForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = [
            "newsletter_is_disabled",
        ]

    def __init__(self, *args, **kwargs):
        super(NewsletterIsDisabledForm, self).__init__(*args, **kwargs)
        self.fields["newsletter_is_disabled"].widget.attrs.update(
            {"class": "form-check"}
        )

mailings/views.py
from django.core import cache
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)

from mailings.forms import (
    MessageForm,
    MailingRecipientForm,
    NewsletterForm,
    NewsletterIsDisabledForm,
)
from mailings.models import Message, MailingRecipient, Newsletter, AttemptToSend
from mailings.services import NewsletterService


class MessageListView(ListView):
    model = Message
    context_object_name = "messages"
    template_name = "mailings_message/message_list.html"

    def get_queryset(self):
        queryset = cache.get("message_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("message_list_view", queryset, 60 * 15)


@method_decorator(cache_page(60 * 15), name="dispatch")
class MessageDetailView(DetailView):
    model = Message
    context_object_name = "message"
    template_name = "mailings_message/message_detail.html"


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailings:message_list")
    template_name = "mailings_message/message_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailings:message_list")
    template_name = "mailings_message/message_update.html"


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy("mailings:message_list")
    template_name = "mailings_message/message_delete.html"


class MailingRecipientListView(ListView):
    model = MailingRecipient
    context_object_name = "mailing_recipients"
    template_name = "mailings_mailing_recipient/mailing_recipient_list.html"

    def get_queryset(self):
        queryset = cache.get("mailing_recipient_list")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("mailing_recipient_list", queryset, 60 * 15)


@method_decorator(cache_page(60 * 15), name="dispatch")
class MailingRecipientDetailView(DetailView):
    model = MailingRecipient
    context_object_name = "mailing_recipient"
    template_name = "mailings_mailing_recipient/mailing_recipient_detail.html"


class MailingRecipientCreateView(CreateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailings:mailing_recipient_list")
    template_name = "mailings_mailing_recipient/mailing_recipient_create.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingRecipientUpdateView(UpdateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailings:mailing_recipient_list")
    template_name = "mailings_mailing_recipient/mailing_recipient_update.html"


class MailingRecipientDeleteView(DeleteView):
    model = MailingRecipient
    success_url = reverse_lazy("mailings:mailing_recipient_list")
    template_name = "mailings_mailing_recipient/mailing_recipient_delete.html"


class NewsletterListView(ListView):
    model = Newsletter
    context_object_name = "newsletters"
    template_name = "mailings_newsletter/newsletter_list.html"

    def get_queryset(self):

        queryset = cache.get("newsletter_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("newsletter_list_view", queryset, 60 * 15)

        newsletters = super().get_queryset()
        for newsletter in newsletters:
            NewsletterService.send_newsletter_emails(newsletter_id=newsletter.id)
        return newsletters and Newsletter.objects.filter(newsletter_is_disabled=False)


@method_decorator(cache_page(60 * 15), name="dispatch")
class NewsletterDetailView(DetailView):
    model = Newsletter
    context_object_name = "newsletter"
    template_name = "mailings_newsletter/newsletter_detail.html"


class NewsletterCreateView(CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy("mailings:newsletter_list")
    template_name = "mailings_newsletter/newsletter_create.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.status = "Создана"
        return super().form_valid(form)


class NewsletterUpdateView(UpdateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy("mailings:newsletter_list")
    template_name = "mailings_newsletter/newsletter_update.html"


class NewsletterDeleteView(DeleteView):
    model = Newsletter
    success_url = reverse_lazy("mailings:newsletter_list")
    template_name = "mailings_newsletter/newsletter_delete.html"


class HomePageListView(ListView):
    model = Newsletter
    template_name = "mailings_message/home_page.html"

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        context["number_of_mailings"] = len(Newsletter.objects.all())
        context["number_of_active_mailings"] = len(
            [
                newsletter
                for newsletter in Newsletter.objects.all()
                if newsletter.status == "Запущена"
            ]
        )
        context["number_of_recipients"] = len(MailingRecipient.objects.all())

        return context

    def get_queryset(self):
        queryset = cache.get("home_page_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("home_page_list_view", queryset, 60 * 15)


class AttemptToSendListView(ListView):
    model = AttemptToSend
    template_name = "mailings_message/attempt_to_send.html"
    context_object_name = "information"

    def get_queryset(self):
        queryset = cache.get("attempt_to_send_list_view")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("attempt_to_send_list_view", queryset, 60 * 15)


class NewsletterIsDisabledView(UpdateView):
    model = Newsletter
    form_class = NewsletterIsDisabledForm
    template_name = "mailings_newsletter/newsletter_is_disabled.html"
    success_url = reverse_lazy("mailings:newsletter_list")

    def form_valid(self, form):
        form.instance.status = "Завершена"
        return super().form_valid(form)

mailings/templates/mailings_message/attempt_to_send.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Статистика</h1>
    <p class="lead text-body-secondary">Информационная страница рассылок и получателей</p>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">{% for info in information %}
            {% if user == info.newsletter.owner %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text h5" style="text-align: center">{{ info.status }}</p>
                        <p class="card-text">Дата и время попытки: {{ info.date_of_attempt }}</p>
                        <p class="card-text">Ответ почтового сервера: {{ info.mail_server_response }}</p>
                        <p class="card-text">Рассылка: {{ info.newsletter }}</p>
                    </div>
                </div>
            </div>{% endif %}{% endfor %}
        </div>
    </div>
</div>
    </div>
{% endblock %}

mailings/templates/mailings_message/base.html
<!DOCTYPE html>{% load static %}
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Astro v5.9.2">
    <title>Курсовая работа №4</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">
    <script src="{% static 'js/color-modes.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">
    <style>
        .bd-placeholder-img{font-size:1.125rem;text-anchor:middle;-webkit-user-select:none;-moz-user-select:none;user-select:none}@media (min-width: 768px){.bd-placeholder-img-lg{font-size:3.5rem}}.b-example-divider{width:100%;height:3rem;background-color:#0000001a;border:solid rgba(0,0,0,.15);border-width:1px 0;box-shadow:inset 0 .5em 1.5em #0000001a,inset 0 .125em .5em #00000026}.b-example-vr{flex-shrink:0;width:1.5rem;height:100vh}.bi{vertical-align:-.125em;fill:currentColor}.nav-scroller{position:relative;z-index:2;height:2.75rem;overflow-y:hidden}.nav-scroller .nav{display:flex;flex-wrap:nowrap;padding-bottom:1rem;margin-top:-1px;overflow-x:auto;text-align:center;white-space:nowrap;-webkit-overflow-scrolling:touch}.btn-bd-primary{--bd-violet-bg: #712cf9;--bd-violet-rgb: 112.520718, 44.062154, 249.437846;--bs-btn-font-weight: 600;--bs-btn-color: var(--bs-white);--bs-btn-bg: var(--bd-violet-bg);--bs-btn-border-color: var(--bd-violet-bg);--bs-btn-hover-color: var(--bs-white);--bs-btn-hover-bg: #6528e0;--bs-btn-hover-border-color: #6528e0;--bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);--bs-btn-active-color: var(--bs-btn-hover-color);--bs-btn-active-bg: #5a23c8;--bs-btn-active-border-color: #5a23c8}.bd-mode-toggle{z-index:1500}.bd-mode-toggle .bi{width:1em;height:1em}.bd-mode-toggle .dropdown-menu .active .bi{display:block!important}
    </style>
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
    </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (dark)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#moon-stars-fill"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span></button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="dark"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>
<header data-bs-theme="dark">
    {% include 'includes/inc_menu.html' %}
</header>
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            {% block tittle %}{% endblock %}
        </div>
    </section>
    {% block content %}{% endblock %}
</main>
<footer class="text-body-secondary py-5">
    <div class="container"><p class="float-end mb-1"><a href="#">Back to top</a></p>
        <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction">getting started guide</a>.</p></div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" class="astro-vvvwv3sm"></script>
</body>
</html>

mailings/templates/mailings_message/message_list.html
{% extends 'mailings_message/base.html' %}

{% block tittle %}
<div class="col-lg-6 col-md-8 mx-auto"><h1 class="fw-light">Страница писем</h1>
    <p class="lead text-body-secondary">Здесь располагаются ваши письма</p>
    <p><a href="{% url 'mailings:message_create' %}" class="btn btn-primary my-2">Добавить новое письмо</a></p>
{% endblock %}

{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"> {% for message in messages %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body"><p class="card-text h5" style="text-align: center">{{ message.topic }}</p>
                        <p class="card-text">Текст письма: {{ message.content|truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            {% if user == mailing_recipient.owner or perms.mailings.can_view_mailing_recipient %}
                            <div class="btn-group"><a class="btn btn-primary"
                                                      href="{% url 'mailings:message_detail' message.pk %}"
                                                      role="button">Посмотреть</a>
                                {% endif %}
                            {% if user == mailing_recipient.owner %}
                            <a class="btn btn-primary"
                                                      href="{% url 'mailings:message_update' message.pk %}"
                                                      role="button">Редактировать</a>
                            <div class="btn-group"><a class="btn btn-primary"
                                                      href="{% url 'mailings:message_delete' message.pk %}"
                                                      role="button">Удалить</a></div>
                            {% endif %}
                            </div>
                            </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    </div>
{% endblock %}